### ISSUE TITLE
Underwater Flashing lights

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/LostIsleBugTracker#397] opened 2023-10-31 18:57 UTC
### Contact Details

Luke

### What happened?

Some funkiness happening with the underwater effects. See image.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Go underwater

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/100382919/22979d31-29f1-4403-8f84-7ffe38e47e60)

**Comment by westonleavitt** [comment] 2024-10-31 18:45
duplicate of #543

**Closed by westonleavitt** 2024-10-31 18:45 UTC
Labels: Triage
